### ISSUE TITLE
Any demand for an example showing Web_jpg but with https images?

### ISSUE THREAD

**Issue by witnessmenow** [Bodmer/TJpg_Decoder#11]
Hey,

Thanks for the library, I've been using with my spotify API library to display album art and my daughter loves it!

{product image removed)

As part of this work I needed to fetch the image off a https source and I was wondering is it worth me submitting a PR with an example of it? it probably could even be included in the original example.

Gist for what I worked on is here, but I would clean it up for a PR:
(link removed)

**Comment by Bodmer** [comment]
An example would be welcome. Ideally it should support both ESP32 and ESP8266, I am not sure what you are using but code for both using https can be [found here](https://github.com/Bodmer/OpenWeather/blob/master/OpenWeather.cpp).

**Comment by Bodmer** [comment]
I have just looked at your gist link. I can see the code is for a bespoke display. To be included the example sketch would need to be converted to a commonly available TFT. Also all potentially revenue earning links would need to be removed.
