### ISSUE TITLE
PSRAM compatibility

### ISSUE THREAD

**Issue by beckmx** [Bodmer/TJpg_Decoder#18]
Hello, I was using your library, and works very nice, I then started piling some more libs but looks like my ram is not enough, I bought an 8m PSRAM module, but looks like in arduino the allocations must be converted, do you see this as a future plan?

**Comment by Bodmer** [comment]
Not sure what you are asking for. What processor are you using?

Maybe an ESP32?  In that case the library will automatically use PSRAM for Sprites if you enable the PSRAM feature in the Arduino IDE.

**Comment by beckmx** [comment]
Okay, I moved into platformio because arduino is not the best fit for compiling with malloc + psram, and it solved the problem :)
