### ISSUE TITLE
Question about ESP32 RAM buffer

### ISSUE THREAD

**Issue by JPMJPM** [Bodmer/TJpg_Decoder#2]
Hi,

Do you think it is possible to decode and display a JPG image located in
a ESP32 RAM buffer ?.

Regards.

**Comment by Bodmer** [comment]
Yes, you can create an array and save the image into that. Perhaps downloaded from the web. Make sure the array is big enough to hold the entire jpeg.

[This may be of interest.](https://github.com/Bodmer/TFT_eSPI/issues/496#issuecomment-567461723)

**Comment by JPMJPM** [comment]
Ok, thanks.
