### ISSUE TITLE
Problem while rendering JPEG Image.

### ISSUE THREAD

**Issue by viveky1794** [Bodmer/TJpg_Decoder#22]
I am doing a project where I need to store my jpeg file into SPIFFS for later use.
I am  using Arduino IDE. So I am  putting 2 JPEG images into "data"  folder.
Then Updating after going "Tool>ESP32 sketch upload" section.

> Arduino IDE
 ESP32 Dev it
Rpi TFT, 480x320, ili9486, SPI protocol at 40Mb

@Problem :
One Image name " AA.jpg " Is rendering. But Second image namely "ABC.jpg" is not rendering. Can anyone suggest the possible reason and solution. 

@Code : 

>#include <stdio.h>
#include <stdlib.h>
#include <stdint.h>
#include <SPI.h>
#include <TFT_eSPI.h>
#include <String.h>
#include <vector>
#include "Arduino.h"
#include <iostream>
// Include the jpeg decoder library
#include <TJpg_Decoder.h>
using namespace std;
     
>TFT_eSPI tft = TFT_eSPI();         // Invoke custom library
#define SPL Serial.println
#define SP Serial.print

>bool tft_output(int16_t x, int16_t y, uint16_t w, uint16_t h, uint16_t* bitmap)
{
   // Stop further decoding as image is running off bottom of screen
  if ( y >= tft.height() ) return 0;

  // This function will clip the image block rendering automatically at the TFT boundaries
  tft.pushImage(x, y, w, h, bitmap);

  // Return 1 to decode next block
  return 1;
}

>void setup() {
  Serial.begin(9600); // DEBUG WINDOW
  //  Serial1.begin(9600, SERIAL_8N1, RXD1, TXD1); // Keypad interface
  //  Serial2.begin(9600, SERIAL_8N1, RXD2, TXD2); // Weight Mechine
  SPI.beginTransaction(SPISettings(40000000, MSBFIRST, SPI_MODE0));

  tft.init();
  tft.fillScreen(TFT_BLACK);
  tft.setRotation(1);
  uint16_t calData[5] = { 329, 3444, 448, 3193, 2 };
  tft.setTouch(calData);
  tft.fillScreen(TFT_BLACK);

  // Initialise SPIFFS
  if (!SPIFFS.begin()) {
    Serial.println("SPIFFS initialisation failed!");
    while (1) yield(); // Stay here twiddling thumbs waiting
  }
  //SPIFFS.flush();
  Serial.println("\r\nInitialisation done."); 
  tft.setSwapBytes(true); // We need to swap the colour bytes (endianess)

  // The jpeg image can be scaled by a factor of 1, 2, 4, or 8
  TJpgDec.setJpgScale(1);

  // The decoder must be given the exact name of the rendering function above
  TJpgDec.setCallback(tft_output);

  // Draw the image, top left at 0,0
   TJpgDec.drawFsJpg(0, 0, "/ABC.jpg"); // Not Wroking
    delay(2000);
}

void loop() {
  TJpgDec.drawFsJpg(0, 0, "/AA.jpg"); // Working
} 
>

@Images :
1 : AA

![AA](https://user-images.githubusercontent.com/29608699/110769285-023d6400-827e-11eb-9baf-8bed77e3e009.jpg)

2 : ABC
![ABC](https://user-images.githubusercontent.com/29608699/110769315-09fd0880-827e-11eb-89c1-b187369f86e4.jpg)

**Comment by Koxx3** [comment]
did you find any solution ? I have the same trouble (panda sample displaying ... my image isn't. no progressive jpg, nothing special)

**Comment by Bodmer** [comment]
I tried the second image above and can confirm that it will not be decoded.  I then openend it in MS Paint, saved it again and it worked fine. Here is that image:

[TJPG_Issue_22p.zip](https://github.com/Bodmer/TJpg_Decoder/files/6214926/TJPG_Issue_22p.zip)

So there must be something incompatible in the format, maybe it contains a "thumb nail image?

**Comment by Bodmer** [comment]
I tried the [JPEGDecoder library](https://github.com/Bodmer/JPEGDecoder) which uses a different decode engine and it reports "Jpeg file format not supported!", so this means it is encoded in an unsupported format.

The JPEGDecoder  library did load the image version posted above.

I ran analysis on the original image and it is in progressive format:

![image](https://user-images.githubusercontent.com/15824805/112706430-ff588b00-8e9b-11eb-8616-3e606607b917.png)
