### ISSUE TITLE
Layering JPGs

### ISSUE THREAD

**Issue by JHershey69** [Bodmer/TJpg_Decoder#3]
I have tried  

TJpgDec.drawFsJpg(0, 0, "/file1.jpg");
TJpgDec.drawFsJpg(194, 89, "/file2.jpg");

Hoping to overlay a smaller image.
Can this be done?

Thanks.

**Comment by Bodmer** [comment]
Yes that should work.

**Comment by JHershey69** [comment]
okay. I tried it again in a separate sketch and it does work. So I must have some conflict in the original sketch. I have no plans for tomorrow so I can stay up all night and find it. Always something.  CLosing this now. Thanks.
