### ISSUE TITLE
LittleFS issue

### ISSUE THREAD

**Issue by videobuff** [Bodmer/TJpg_Decoder#33]
On a fresh Arduino IDE install i get this error when trying the compile example called All_LittleFS for a ESP32 WROVER.
The FS utilities for ARDUINO IDE are installed for esp32 and esp8266, so i can upload data files to the ESP32.

> Alternatives for LittleFS.h: []
> ResolveLibrary(LittleFS.h)
>   -> candidates: []om D:\Documenten\Ham4you Rotor systeem\test-wt32-sco1\test-wt32-sco1.ino:57:0:
> D:\Documenten\Arduino\libraries\TJpg_Decoder\src/TJpg_Decoder.h:23:26: fatal error: LittleFS.h: No such file or directory
> 

Running a Win10 machine and i can find LittleFS.h in the following directories: (see the picture)
I can't figure out how to solve this so that Arduino IDE is finding it. The library Tjpg_decoder is installed using the libray manager.
Any help is much appreciated.

![LittleFS directories](https://user-images.githubusercontent.com/3132953/152034447-56ffee83-21eb-4e6d-97dd-5b478d5fdde8.jpg)

**Comment by Bodmer** [comment]
You will need ESP32 board package 2.0.0 or later, which has LittleFS built in. 

See also #30.
