### ISSUE TITLE
Error on compiling - looking for LittleFS.h

### ISSUE THREAD

**Issue by noersaleh** [Bodmer/TJpg_Decoder#36]
In file included from C:\Users\noers\My Drive (noersaleh.smarthome@gmail.com)\Arduino\TTGO\TTGO_ESP32CAM_WiFi_Direct\TTGO_ESP32CAM_WiFi_Direct.ino:4:0:

C:\Users\noers\My Drive (noersaleh.smarthome@gmail.com)\Arduino\libraries\TJpg_Decoder-master\src/TJpg_Decoder.h:23:26: fatal error: LittleFS.h: No such file or directory

compilation terminated.

exit status 1
Error compiling for board TTGO LoRa32-OLED V1.

**Comment by Bodmer** [comment]
Use the latest ESP32 board package. 2.0.x includes LittleFS.

**Comment by Bodmer** [comment]
I have updated the ReadMe.

**Comment by noersaleh** [comment]
Thanks a lot bro.. It works
