### ISSUE TITLE
only a red screen comes up on my esp32-s2 board

### ISSUE THREAD

**Issue by hannescam** [Bodmer/TJpg_Decoder#37]
it detects the file with All_SPIFFS but only a red screen and it says the image has a resolution of 0x0
please help
thanks

**Comment by Bodmer** [comment]
Does the unmodified example show this behaviour or is the example modified? Make sure plenty of space is allocated for SPIFFS.

Which ESP32 board package version are you using?

SPIFFS is deprecated so maybe try LittleFS which is also faster.

**Comment by hannescam** [comment]
i have no modification made just the raw example
the pakage is ESP32S2 Dev Module
with my homemade esp32-s2 board
and the scematic is in pdf here send
i bridged the FE1.1 that means only the cp2104 has a connection

**Comment by Bodmer** [comment]
I have tested the sketch with a ESP32-S2 and ILI9341 display and it is working.

This is the serial output:
```
 Testing TJpg_Decoder library

Initialisation done.
/Baboon40.jpg 320x480 1:2 185 ms
/panda.jpg 240x320 1:1 110 ms
/tiger.jpg 240x320 1:1 189 ms
```
Post your serial output.

Also try the Flash_Jpg example as that does not need SPIFFS to be configured and no data files have to be uploaded.

This is the serial output I get with that sketch:
```
 Testing TJpg_Decoder library
Width = 240, height = 320
99 ms
```
Post your output to that sketch as well.

**Comment by hannescam** [comment]
it is working with littlefs and the flash_jpeg 
but with littlefs it only showed a red display and this output:` Testing TJpg_Decoder library

Initialisation done.
1.jpg
/1.jpg 0x0 1:1 30 ms
`
and with the tiger it was working all fine the pictures are attached
i experimented with the first one but never showed any diference
![6](https://user-images.githubusercontent.com/88653399/159185034-2309ffd5-3d4e-418d-97ac-e03aee93c0ac.jpg)
![7](https://user-images.githubusercontent.com/88653399/159185036-53b3da73-3978-4f1a-9628-71d9dadf28da.jpg)
![8](https://user-images.githubusercontent.com/88653399/159185038-b30065b4-1e3e-4e39-a4f4-8bf6c503d893.jpg)
![9](https://user-images.githubusercontent.com/88653399/159185039-bda7f90f-c907-4823-9b29-015853f92809.jpg)

![1](https://user-images.githubusercontent.com/88653399/159185026-921352df-bab8-47a2-b04c-1db1ab888de4.jpg)
![2](https://user-images.githubusercontent.com/88653399/159185029-38c50f47-7a55-4379-afe6-5ac38e7466ab.jpg)
![3](https://user-images.githubusercontent.com/88653399/159185030-3a128b9f-943b-4826-aea2-72016151739f.jpg)
![4](https://user-images.githubusercontent.com/88653399/159185032-c2541dd7-e1bd-484e-947a-0a46b1781c75.jpg)
![5](https://user-images.githubusercontent.com/88653399/159185033-17677132-f33f-4812-81ae-5890c457daf1.jpg)
d

**Comment by Bodmer** [comment]
Ah! So you are modifying the example with you own files!

Not sure what the 1 and 2 are but the links just give me errors.

**Comment by hannescam** [comment]
i left the original files also on there and they worked flawlessly

**Comment by hannescam** [comment]
here are the pics: [link](https://github.com/hannescam/pics-for-bodmer)
1 and 2 are these from above and the rest 3 - 9 are all others

**Comment by Bodmer** [comment]
I had a look at image 1.jpg and it is in 8 bit format which the decoder does not support. Jpegs must be 24 bit. Here is one converted and it loads fine.

To convert I loaded it into MS Paint and then just did a saveas:
[1x.zip](https://github.com/Bodmer/TJpg_Decoder/files/8320333/1x.zip)

**Comment by Bodmer** [comment]
I have updated the ReamdMe to make this clearer. Thanks for reporting this.

**Comment by hannescam** [comment]
thankyou i had a txt to png converter script set for greyscale and i uploaded te png to a converter website and put the jpg file in the spiffs erlier and now littlefs
