### ISSUE TITLE
Animated_dial Compliation error - ESP32 / ILI9341

### ISSUE THREAD

**Issue by Amitabh-wq** [Bodmer/TJpg_Decoder#38]
Hi, I am trying to test the example called 'Animated_dial' but geting the IDE error:

I:\Users\UserJ\Documents\Arduino\libraries\TJpg_Decoder\src/TJpg_Decoder.h:23:26: fatal error: LittleFS.h: No such file or directory

I have installed all the libraries required. Any toughts? Thanks

**Comment by Bodmer** [comment]
Load the latest master jpeg library and try that.

**Comment by Amitabh-wq** [comment]
> Load the latest master jpeg library and try that.

Hi Bodmer, I am using the TJpg_Decoder latest version 1.0.3 but it has the above compilation error.

**Comment by Bodmer** [comment]
I checked with board package 2.0.2 (latest) and it runs fine and LittleFS.h is found.

I suspect you are using an old 1.0.x board package as those version did not provide LittleFS support.

**Comment by Amitabh-wq** [comment]
I did the following, I edited the header 'TJpg_Decoder.h' (from the TJpg_Decoder library) I renamed the call of library from <LittleFS.h> to <LITTLEFS.h>, as the LITTLEFS library is in capital letters. I use ESP32 boards V 1.0.6 which is the most stable for my projects. The compilation went without errors, but the graph has problems, the pointer is erasing the numbers, see the photo below:
![IMG_2061](https://user-images.githubusercontent.com/89787514/166568706-9a85e93d-c48e-41cb-97a6-b839fd7a5b9b.JPG)

**Comment by Amitabh-wq** [comment]
In addition, before I also tested ESP Boards V 2.0.2 and this same error occurred.

**Comment by Bodmer** [comment]
The display SDO line must be connected. Have you specified the read frequency in the setup file?
#define SPI_READ_FREQUENCY  10000000

**Comment by Amitabh-wq** [comment]
Hi Bodmer, I followed your instructions and it worked. Only the numbers in the center are overlapping, I don't know if this is normal. See below

https://user-images.githubusercontent.com/89787514/166835163-2129088c-a6c5-4313-82e5-4917404a16fa.mp4

.

**Comment by Bodmer** [comment]
The numbers problem has been fixed in the latest master library on Github.

**Comment by Amitabh-wq** [comment]
I am using the latest.
![image](https://user-images.githubusercontent.com/89787514/166847154-3ac717a6-7225-4549-baed-cac28f774878.png)

**Comment by Bodmer** [comment]
Latest is 2.4.61 and is only available from Github here a the moment:
https://github.com/Bodmer/TFT_eSPI

**Comment by Amitabh-wq** [comment]
> Latest is 2.4.61 and is only available from Github here a the moment: https://github.com/Bodmer/TFT_eSPI

I have installed it manually and replaced with my configurated files. Now it is working fine. Thank you.

**Comment by Bodmer** [comment]
Great, I will be releasing the new version soon.

**Comment by IAmOrion** [comment]
I'm curious, where are you getting 2.0.2 package from? I came here with the same "LIttleFS" not found problem.  I say @Amitabh-wq comment to use uppercase LITTLEFS and that has worked for me.  As far as I know I have the correct board url > https://raw.githubusercontent.com/espressif/arduino-esp32/gh-pages/package_esp32_index.json and there's no 2.x.x version?

<img width="768" alt="Screenshot 2022-07-23 at 19 48 18" src="https://user-images.githubusercontent.com/3501380/180618935-5d60c63f-9249-4702-be16-4d95894c6144.png">

**Comment by Bodmer** [comment]
Currently I am using the development branch link:
https://raw.githubusercontent.com/espressif/arduino-esp32/gh-pages/package_esp32_dev_index.json
