### ISSUE TITLE
Option for More Data?

### ISSUE THREAD

**Issue by Davarco** [Bodmer/TJpg_Decoder#4]
Based on what I can tell from the lib, the decoder converts each RGB pixel to a uint16_t. This means that we can extract 5 bits of R data, 6 bits of G data, and 5 bits of B data. Is it possible to instead get the full 8 bits for all 3 colors, so RGB888 format?

**Comment by Bodmer** [comment]
Yes, just [change the tjpgd.h parameter here](https://github.com/Bodmer/TJpg_Decoder/blob/master/src/tjpgd.h#L10) to 0.
You will need to change the buffer to 8 bit pointer type [here](https://github.com/Bodmer/TJpg_Decoder/blob/master/src/TJpg_Decoder.cpp#L155) and also in the sketch callback.

You will then get 3 bytes per pixel.
