### ISSUE TITLE
TJpgDec.getJpgSize

### ISSUE THREAD

**Issue by joseph-vedadi** [Bodmer/TJpg_Decoder#40]
I do not know how to convert the image to binary 
I used the web-tool provided for diff image the size is zero ... 

```
TJpgDec.getJpgSize(&w, &h, img, sizeof(img));
```
what is the specification of the image, and why it is zero ?
```
08:48:20.252 ->  Size of: 2446
08:48:20.286 -> Width = 0, height = 0
08:48:20.321 -> 0 ms

```

**Comment by Bodmer** [comment]
I now use the tool and[ instructions detailed here](https://github.com/Bodmer/TFT_eSPI/discussions/1843).

Jpeg file arrays should start with the marker values: 0xFF,0xD8,0xFF,

**Comment by joseph-vedadi** [comment]
@Bodmer Thank you but I still have the same issue 

<img width="937" alt="image" src="https://user-images.githubusercontent.com/17168374/170563347-b5c2afb4-e613-4533-847c-d98b9472138c.png">
![Hnet com-image (1)](https://user-images.githubusercontent.com/17168374/170563397-abe5a4ca-0639-484e-b411-1aacfdf251e5.png)

**Comment by Bodmer** [comment]
A PNG format file cannot be decoded with a jpeg decoder. Convert the png to a jpeg first with an image handling program like GIMP or MS Paint. Alternatively use a PNG decoder library.
