### ISSUE TITLE
Redraw TFT image if TFT SDO/MISO output is unavailable

### ISSUE THREAD

**Issue by hansaplasst** [Bodmer/TJpg_Decoder#53]
Hi Bodmer,

I'm testing the Animated_dial example with an ESP8266 and [GC9A01 round display](https://nl.aliexpress.com/item/1005004342510301.html) without SDO/MISO. This means that with the existing code you cannot write image data over an existing background image without erasing (parts of) the data.

Without MISO however, we could use parts of the original background image data from dial.h to but back clean image data to the TFT? Is this possible with your function library?

**Comment by Bodmer** [comment]
Yes, it is possible and I have written an experimental sketch that works that way. I will see if I can find it.

**Comment by hansaplasst** [comment]
Thanks for the quick reply! That would be awesome!

**Comment by Bodmer** [comment]
It think I must have archived, it will be a couple of days before I can run a search.

**Comment by Bodmer** [comment]
There is an example here:
https://github.com/Bodmer/TFT_eSPI/discussions/860#discussioncomment-208303

However you may find the esp8266 does not have sufficient RAM.

**Comment by hansaplasst** [comment]
Thanks! I will check it out.

**Comment by hansaplasst** [comment]
That example worked out great!
Here is what I've come up with.

[Animated_dial_noTFTrd.zip](https://github.com/Bodmer/TJpg_Decoder/files/9932935/Animated_dial_noTFTrd.zip)

Thanks again for your help!

**Comment by hansaplasst** [comment]
BTW.   Does the pivot point need to be within a sprite's boundaries (width and height)?

**Comment by Bodmer** [comment]
No, it can be outside. See notes [here](https://github.com/Bodmer/TFT_eSPI/blob/master/examples/Sprite/Rotated_Sprite_1/Rotated_Sprite_1.ino#L4-L6).

I tried your animated dial example and it works well and fast on an RP2040 with parallel display. Excellet!  I had some stray red pixels left by the tip of the needle.
