### ISSUE TITLE
Cannot run on ESP32

### ISSUE THREAD

**Issue by Staccato-kashi** [Bodmer/TJpg_Decoder#56]
I used someone's project written for ESP8266, and I'm trying to transplant it to my ESP32 based board on Arduino IDE, then I found that it could work on ESP8266 but not on ESP32-PICO. I've already sodered the chip on board… So is there anyway to make it enable on ESP32?

**Comment by Bodmer** [comment]
The library has been tested with the ESP32.

Have you run some of the examples provided with the library?

**Comment by Staccato-kashi** [comment]
> The library has been tested with the ESP32.
> 
> Have you run some of the examples provided with the library?

I tried "Flash_array" and "All_LittleFS", but nether of them works…or I should describe it more explicit, it cannot be verified. I think this because ESP32-PICO does not provides "LittleFS" library, but I don't know how to load it from another directory and compile it with new directory.
![image](https://user-images.githubusercontent.com/50204220/204740986-05c2b53a-74e7-4766-abeb-fa00ca251d72.png)

**Comment by Bodmer** [comment]
The library needs to be used with a graphics library, which library are you using and do the examples for it work?

**Comment by Bodmer** [comment]
I see from the screen shot that you are using TFT_eSPI, so run the Read_User_Setup sketch and verify it is as expected. Check other graphics examples work.

Check you are using the latest ESP32 Arduino board package 2.0.5,  older packages than 2.0.0 do not provide LittleFS.

**Comment by Staccato-kashi** [comment]
Thanks for your help. It's my fault that I only tried to install ESP32 board package from _dl.espressif.com_ but not other way… I did't know the newest board package is on GitHub. I'm sorry to bother you about my careless mistake. (And my poor English, if so.)
