### ISSUE TITLE
Problem with specific SDcards

### ISSUE THREAD

**Issue by cobungra** [Bodmer/TJpg_Decoder#58]
Hello, If you have a moment, I'd like your opinion.
I have had great success with TJPG_Decoder and TFT_eSPI (thanks!)
I recently bought a batch of SDcards which refuse to render the entire image on screen.
There is no problem reading the files. I can even send them from the SDcards and view the images via HTTP.
All of my other SDCards work fine...
I'm happy to bin these, but I just wonder what's going on?
(Using SD_Jpg Example / TJpg_Decoder 1.0.8)
Cheers.
Photos show the same image, same hardware and software but different brand of SDCard. (I have ten, same performance, ready for public disgrace...)

![bad](https://user-images.githubusercontent.com/25142892/206829383-cfb3e189-eeb9-4acb-af06-195228b25aae.jpg)
![good](https://user-images.githubusercontent.com/25142892/206829389-3b1b2661-253a-414d-82c6-db050c63a9e9.jpg)

**Comment by cobungra** [comment]
Not a problem for TJpg_Decoder. 
Thanks.

**Comment by Bodmer** [comment]
Hi, glad to hear that. Thanks for reporting that.
