### ISSUE TITLE
NV12 format to jpeg

### ISSUE THREAD

**Issue by beckmx** [Bodmer/TJpg_Decoder#60]
Hello Bodmer, I have images (frames) from a video coming in nv12 format (not jpeg) I want to convert that into JPG, so, basically I have an algorithm to move bytes as corresponding, but the actual "compress" into jpeg is what I would like to achieve, I was wondering if this is possible with your library, graphically it would be something like:

`nv12 (raw format)->arrange pixels->compress to jpg`

**Comment by Bodmer** [comment]
The library does not incorporate a jpeg encoder. There is an encoder library here that looks suitable:
https://github.com/bitbank2/JPEGENC
