### ISSUE TITLE
Could we ask for v1.1.0 tag

### ISSUE THREAD

**Issue by ivankravets** [Bodmer/TJpg_Decoder#71]
- https://github.com/Bodmer/TJpg_Decoder/releases
- https://github.com/Bodmer/TJpg_Decoder/blob/master/library.json
- https://github.com/Bodmer/TJpg_Decoder/blob/master/library.properties

The `version` field is updated on both manifests but there is no `v1.1.0` tag for them.

Thanks!

**Comment by Bodmer** [comment]
Done

**Comment by ivankravets** [comment]
Thanks! https://registry.platformio.org/libraries/bodmer/TJpg_Decoder
